# Generated by Django 5.1.6 on 2025-04-25 20:49
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('resim', models.ImageField(upload_to='urun_resimleri/')),
                ('aciklama', models.TextField(blank=True)),
            ],
        ),
    ]